"""Migration message

Revision ID: 03c03d0b9d85
Revises: 1d49359fa038
Create Date: 2020-04-12 23:53:04.412065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c03d0b9d85'
down_revision = '1d49359fa038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###