"""Migration message

Revision ID: 1d49359fa038
Revises: 2438e2df9e5a
Create Date: 2020-04-12 23:49:20.768119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d49359fa038'
down_revision = '2438e2df9e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###