"""Migration message

Revision ID: 2438e2df9e5a
Revises: 6360d060144a
Create Date: 2020-04-12 23:05:03.134442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2438e2df9e5a'
down_revision = '6360d060144a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role')
    )
    op.create_table('users',
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('state', sa.Enum('active', 'archived', 'deleted', name='statetype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_unique_user_content', 'users', ['name'], unique=True, postgresql_where=sa.text("state = 'active'"))
    op.create_table('users_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_roles')
    op.drop_index('ix_unique_user_content', table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###