version: "3"

services:
  database:
    restart: always
    image: postgres:10.1
    environment:
      - POSTGRES_USER=emr_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=emr_user    
    volumes:
      - ../emr_user:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    expose:
      - "5434"
    container_name: emr_user
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: emr_redis
  app:
    restart: always
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ${PWD}:/app
    depends_on:
      - database
    stdin_open: true
    tty: true
    container_name: emr_api
