version: "2.1"
services:
  database:
    restart: always
    image: postgres:10.1
    
    volumes:
      - ../emr_user:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    container_name: emr_user
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: emr_redis
  app:
    restart: always
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ${PWD}:/app
    depends_on:
      - database
    stdin_open: true
    tty: true
    container_name: emr_api
